### ISSUE TITLE
getConfirmations gives [] even if there are "Awaiting Mobile Confirmation" trades

### ISSUE THREAD

**Issue by lopataz** [DoctorMcKay/node-steamcommunity#27]
So, I implemented getConfirmations as follow:

```javascript
function getconf(){
               
 var timekey=Math.round(Date.now() / 1000);
		var confirmationkey = SteamTotp.getConfirmationKey(identitySecret, timekey, "conf");
		
		community.getConfirmations(timekey, confirmationkey, function(err2,confirmations){
			if(err2){
				console.log(err2);
			}else{
				console.log(confirmations); //Gives '[]' even if there are waiting trades
				confirmations.forEach(function(conf,index,array){
					setTimeout(function(conf){
						var timekey2=Math.round(Date.now() / 1000);
						var confirmationkey2 = SteamTotp.getConfirmationKey(identitySecret, timekey2, "allow");

      community.respondToConfirmation(conf.id,conf.key,timekey2,confirmationkey2,true,function(err){
							console.log(err);
						});
					},index*1500,conf);
				});
			}
		});
}
```
I call getconf every 40 seconds
But when I send some offers sometimes I don't get the confirmations for it.
It does it very frequently! and the confirmations never appears, but the next confirmation appear ometimes.
Here is the screenshot of the sent offer : https://gyazo.com/d1a842e92af53817e2aa939498d0a162
Here is the screenshot of the community.getConfirmations response (empty array []): https://gyazo.com/2a41c7211a53d3971341bea3cdd1ab04

**Comment by kenzik** [comment]
Can confirm, this happens with me also.

**Comment by charredgrass** [comment]
Also happens with me and I'm polling confirmations using [`startConfirmationsChecker`](https://github.com/DoctorMcKay/node-steamcommunity/wiki/Steam-Confirmation-Polling#startconfirmationcheckerpollinterval) - the newConfirmation event is never called.

**Comment by DoctorMcKay** [comment]
Like nothing ever, or just sometimes?

**Comment by kenzik** [comment]
It happens for some trade offers, not all, like 80-90% of the confirmations work and show up and the other just disappear.

**Comment by DoctorMcKay** [comment]
Sounds like a problem on Steam's end. I've experienced stuff like this, but changing the device ID in the URL fixed it for me. For that reason, the module uses a different device ID every time it requests the page.

**Comment by Lagg** [comment]
Can confirm reproducability of this.

**Comment by Lagg** [comment]
Alright so it will emit newConfirmation one more time if I call checkConfirmations.  Not exactly in the spirit of clean polling. But I'm busy debugging my own stuff right now. Wish I could help more :(

**Comment by DoctorMcKay** [comment]
@Lagg Is it not polling or something? I can't imagine what checkConfirmations would do that regular polling wouldn't.

**Comment by Lagg** [comment]
Honestly not sure right now. Something strange is happening with steam. When I enabled trade confirmations for an account, it gave a "can not act on confirmation" error, but showed the trade offer as approved (as in literally ready state 2 and showing confirmation method 2). Then when I disabled them it didn't even send me an email to opt out and just did it, *then* when I tried enabling them again every offer that was  marked sent reverted to needing mobile confirmations, and yet steam is not returning any confirmations whatsoever. So needless to say it could be a deeper problem.

**Comment by DoctorMcKay** [comment]
Agreed, trading is completely screwed right now for me. I send an offer from an alt to my main account, confirm it on the alt, and it appears Active to the alt. But my main account doesn't see it at all.

I also did a real-time trade between the two with only the alt losing items. Confirmed it, and the offer went into that same Active-but-only-shows-up-to-me state.

**Comment by Lagg** [comment]
Um... Okay... So it looks like steam sends opt-out confirmation as a confirmation... Didn't know that. Explains the lack of link

```
    title: 'Confirm Opt-Out of Trade Confirmation Emails',
    receiving: '',
    time: 'Just now',
    icon: '' } ]
```

Which I was able to accept just fine, but actual offers are problematic. This is crazy.

**Comment by lopataz** [comment]
I think I found the solution to my question:

I set a longer timeout between each time an offer is sent 9 seconds)

And now the confirmation is set for every offer

**Comment by Lagg** [comment]
One other thing possibly worth noting. I can't figure out the relationship or lack thereof of accounts that do this. My test bot gets and accepts confirmations just fine. And this is a test bot - so never been touched besides the prerequisite $5. It didn't even have any items at first either.

**Comment by halipso** [comment]
same happens to me.
any way to fix it?

**Comment by Lagg** [comment]
Oh there's always a way to fix this stuff. It's just that Valve doesn't generally like taking responsibility for their bugs, especially in situations where deadlines are imposed for activation. Just continue trying to figure out attributes that could be causing this and report any suspicious data in this issue. It'll help all of us, especially mckay.

**Comment by lopataz** [comment]
if that can help I made a function to automatically resend not confirmed offers. I call this function just after responding to all current confirmations:

```

function sendfail(lasttime){
	offers.getOffers({ get_sent_offers: 1,
						  active_only: 1
						}, function(error, body) {
						  if(body !== undefined && body.response.trade_offers_sent){
							body.response.trade_offers_sent.forEach(function(offer) {
								if(offer !== undefined && offer.items_to_give !== undefined && offer.time_created < lasttime-4 && offer.trade_offer_state==9){
									offers.cancelOffer({tradeOfferId: offer.tradeofferid},(function(offer){ return function(err){											fn.gettradetoken(offer.steamid_other,function(partner,token){ // your own function to get the token etc
												if(partner !== undefined && token !== undefined && offer!== undefined && offer.items_to_give !== undefined){
													offers.makeOffer ({
														partnerAccountId: partner,
														accessToken:token,
														itemsFromMe: offer.items_to_give,
														itemsFromThem: [],
														message: ''
													},function(err1, response){
														
													});
												
												}
											});		
										
									};})(offer));
									
								}						 
							});
						  }
						});
	
}
```

Unfortunately this works 20 minutes, but when we get too many unconfirmed offers; The offers.getOffers({ doesn't work and nothing is working no more

**Comment by halipso** [comment]
Yeah i did the same.
Just resending an offer.

**Comment by Lagg** [comment]
You guys will want to be careful about when you cancel offers starting on the 9th. I believe there's an account lock.

**Comment by scholtzm** [comment]
Hopefully it should be safe to cancel if you have 2FA+mobile confs enabled. (???)

**Comment by Lagg** [comment]
Nope, I think this was actually part of the outrage that started the petition stuff in the first place. The lock occurs even then from what I understand. Of course, since there's no unambiguous documentation available we can't be sure until it happens.

**Comment by scholtzm** [comment]
With the limit of 30 pending trade offers, if cancelling was punished with a 3 day lock, every active bot will get locked down pretty fast. Hopefully, that's not the case.

**Comment by DoctorMcKay** [comment]
I have spoken with a Valve employee regarding this. You cannot cancel escrow'd trades individually. There will be a "I was hijacked, lock everything down" button that cancels all escrow'd trades and active trade offers. As long as you don't click that, there's no trade lockdown.

**Comment by kenzik** [comment]
Escrow'd trades are the one's that have 3 day limit? If I cancel the trades that have pending mobile confirmation then I'm fine?

**Comment by charredgrass** [comment]
@kenzik Yes, you *should* be fine - but we really don't know that much about the technicalities of Escrow until it's in effect.

**Comment by Lagg** [comment]
Hopefully the same is not true of this current bug.

**Comment by scholtzm** [comment]
> You cannot cancel escrow'd trades individually. 

So once the trade gets into escrow, the items are locked for 3 days and we cannot get them back?

**Comment by andrewda** [comment]
@scholtzm Unless you lock your account and cancel *all* active trades, yes, I think that's correct.

**Comment by lopataz** [comment]
Can someone confirm? It seems that the getConfirmations fails after ~1024 seconds. and start working again for the next offers.

**Comment by scholtzm** [comment]
I have also noticed that I was unable to retrieve trade offer ID for certain confirmations. The trades that failed were roughly 50 minutes old at the time.

**Comment by andrewda** [comment]
@scholtzm Could this be because of how messed up trade offers were yesterday? There were a ton of issues on Steam's end yesterday, so that might be why those ID retrievals failed.

**Comment by Lagg** [comment]
Can anyone confirm/disconfirm that the issue with the ghost-whisperer shit going on with the trade offers is resolved? I've been poking around the sub the reddit thread is on and people were steadily reporting the issue but now it appears to have dropped off. I can't test myself at the moment since my two test bots always worked and I still saw a white page on the confirmations in the official app. But that could just as easily indicate steam's "standard" timeouts.

**Comment by lopataz** [comment]
This still doesn't work for me: as kenzik said : 80% of the offers work but 10-20% don't

**Comment by lopataz** [comment]
May the issue come from [that line](https://github.com/DoctorMcKay/node-steamcommunity/blob/master/components/confirmations.js#L144)

I tried to change the value with the serial_number , and it seems to work better 95% of the time

**Comment by antonsekatski** [comment]
Maybe it's because of a random string passed to the activation method at [that line](https://github.com/DoctorMcKay/node-steamcommunity/blob/master/components/twofactor.js#L21)? Maybe we need to save it somewhere and use it later?

I presume, Steam uses Android/iOS device_id value for that and it's always the same.

**Comment by lopataz** [comment]
That's it! 
or at least a value that isn't taken by someone else (unlike android:'+time.now();)
Just set pid a single time when you start the server:
```javascript
var pid = require('crypto').createHash('sha1');
pid.update(Math.random().toString());
pid = pid.digest('hex');
```
then pass it to the p parameter request

**Comment by DoctorMcKay** [comment]
You sure about this? In my experience you're more likely to get stale data by using the same value each time.

**Comment by Lagg** [comment]
The question is - assuming that this wasn't a fluke - why do they work better in that situation. And why still only 95% of the time? 5% is still not exactly an acceptable margin for potentially either having no way to confirm a trade or having steam just completely lie about offers being confirmed and showing them as such. Usually this works in the entirely opposite direction in that using different fingerprints is supposed to help *guarantee* fresh data :(

**Comment by DoctorMcKay** [comment]
I agree with @Lagg. In my experience, using a different deviceid gives more fresh data, which makes sense with how caching systems usually operate. If the issue is that people are getting the same deviceid as someone else (which I find to be unlikely to be happening very frequently since it's down to the millisecond), then it's trivial to replace it with a truly random value.

I'm going to swap it out for a random value when I get a chance. That should hopefully help, I would think.

**Comment by lopataz** [comment]
I tried with a random value initiated when the server starts, but it still doesn't work

**Comment by scholtzm** [comment]
What's the behaviour of official mobile app? It uses static ID, right?

btw. SteamAuth uses single ID for enabling 2FA and then for every confirmation.

**Comment by DoctorMcKay** [comment]
As far as I know, the official app uses the same ID for enabling and for confirmations. The problem there is that if you enabled with node you probably used a random deviceid that can't be retrieved now. We could still use the same deviceid for each request but again, in my experience using the same ID is much more likely to give you back bad data than using a random one (which is expected behavior from a caching system).

**Comment by Lagg** [comment]
If the device ID is at all required by Valve to be anything besides whatever the client feels like. I'm just going to say this now: They already failed at utilizing a very awesome OTP spec properly and there's a major bug 2 days before release. This would be bad, possibly with security implications. Because if the ID can be used in any way for authentication, keying or is any way compared to an identity datum they've made the key weaker by default. Despite the quite frankly betrayed feeling and loss of respect, I'm pretty sure they're smarter than this.

I hope :(

**Comment by Desp163** [comment]
What happens if first confirmation didn't pop and then you send second trade? Does two notifications show up?
Because this is how random steam trades and emails were getting stuck for a while.

**Comment by lopataz** [comment]
@Desp163 
The second trade appear without the first one,
The first trade will never pop

**Comment by DoctorMcKay** [comment]
v3.14.1 uses truly-random machineids, maybe see if that resolves your issues.

**Comment by DoctorMcKay** [comment]
Just a note: I've deployed 3.14.1 into production and I'm experiencing about 5% failure. Failures seem to be clustered around each other.

**Comment by scholtzm** [comment]
Does the trade confirmation just never appear?

**Comment by Miwwa** [comment]
I use always one deviceId for one bot, but have same issue

**Comment by DoctorMcKay** [comment]
I'm not totally sure. I just check my confirmations 5 times after I send an offer, and if it's not there I just cancel it.

**Comment by Lagg** [comment]
That'll work great until one starts running into issues with the servers throttling them. Really surprised in a not-good way that it's 1 day before this thing and I still see blanks even in the app sometimes. Can't say I have a better idea I suppose.

**Comment by DoctorMcKay** [comment]
After running overnight I have a failure rate of 3.6%.

**Comment by Lagg** [comment]
Well your stat report was good enough for me to trust so I bit my lip and bent over and enabled confirmations for the same bot I mentioned earlier.

And it accepted them fine. This inconsistent behavior is really what is the worst. Anyway, not sure if the offer is invisible to the other party yet.

**Comment by emko** [comment]
Does anyone know if the Android app has the same problem?

**Comment by scholtzm** [comment]
@DoctorMcKay What was the failure rate for you before Escrow?

**Comment by laterbreh** [comment]
I can't confirm nor deny that this is an issue for me unfortunately. I've confirmed over 100 trades today and they all went through... God knows when we go to production the problem will arise. 

The point of my post is just to add some more information. This is what I am doing:

var code = SteamTotp.generateAuthCode('your code here', timekey);
var timekey = Math.round(Date.now() / 1000);

(using steam user on the client.on('webSession'))
community.setCookies(cookies);
community.startConfirmationChecker(10000, identity_hashed);

I also included this from the documentation:

community.on('confKeyNeeded', function(tag, callback) {
    var time = Math.floor(Date.now() / 1000);
    console.log('Conf Key Needed');
    callback(null, time, SteamTotp.generateAuthCode('your key here', time, tag));
});

and finally 
community.checkConfirmations(); after each sent trade. 


I will continue to do more testing today... I hope the information I provided will be useful to someone here running into the problem. I'll report back what my error rate is once I deploy this to production when escrow goes live. 

Good luck everyone.

**Comment by Lagg** [comment]
Might as well leave my own then: I've successfully enabled confirmations on 4 bots of a fleet of 25. All 4 of which were experiencing the confirmations problem (and additionally a plethora of 401s and  "cannot act on confirmation"s). They've all made several offers between the time I enabled them and now, and none slipped through. The code I'm using is mildly more complex than @laterbreh 's due to handling the events myself, but functionally it's the same as what the automatic ones do. I also do the callbacks for confKeyNeeded in a similar manner.

Will likely report back here if I can when the rest are enabled. But things are looking optimistic. Don't know if this is a result of your fixes or what @DoctorMcKay but thanks for the modules regardless.

**Comment by laterbreh** [comment]
@Lagg After reading your thread something hit after re-reading my bot. I am still using a sentry file. My plan was to remove this since i assumed with the steam-totp it would be irrelevant, but I forgot to remove this. So my bot is still using a sentry file, and was using one all day when I was doing testing. 

I have no idea if that makes the difference or not but I thought I would share: client.setSentry(fs.readFileSync('sentry'));

Ill continue to update as I find out more.

**Comment by Lagg** [comment]
I assume they still are relevant. I mean we still use steamMachineAuth which is more likely than not just a hash of a sentry valve has on their servers while the client has its own. But yeah in any case I'm using the same call right before logOn.

**Comment by Lagg** [comment]
Update: I enabled the whole fleet, all seems to be well. Or at the very least the same errors and issues aren't happening. I would like to think that means it was fixed and recommend that this be closed. But I don't trust valve nearly enough for that. Especially after what happened that resulted in this thread in the first place, so take it how you will.

**Comment by DoctorMcKay** [comment]
@scholtzm That number is only the rate of failure among offers that were sent successfully, but couldn't be confirmed.

**Comment by lopataz** [comment]
It's not Steam, it's our implementation. I have tested it with my smartphone and all the trades confirmation go through.
However on my bots I have 5% of fails and sometimes it no more confirmation will appear.
 Does not renewing the conf key can help?

**Comment by andrewda** [comment]
@lopataz I think it is in fact Steam. I have witnessed two occurrences (out of at least 150 trades) where I simply never receive the trade confirmation, and the only way to get it is to cancel and rerun the trade. I've been using Steam Mobile confirmations since Day 1 that they were released, so I have a lot of trades under my belt with it. In my experience at least, the success rate is significantly higher in the app, but still not perfect.

**Comment by Lagg** [comment]
Because the community has been helpful to me in many ways during this update I might as well try to continue reporting what I notice since I have a pretty decent testing set. When updating to fix the escrow_end_date attribute error (thank you so goddamn much for the prompt fix & merge @DoctorMcKay and @lincsanders - loving that I've only needed to downstream patch once for this) I noticed that sometimes both confirmations and trade offer URLs will return 404s, thus leading to the offerID attr being null and offer page itself claiming invalidity. However, steam still responds perfectly in line with what it usually does when accepting confirmations. So I'm not sure what kind of effect it's having on the offer. But it definitely still confirms it and returns no data indicating errors besides the nulled offerID. So account for that if you must.

**Comment by DoctorMcKay** [comment]
1.1% failure out of around 23k confirmations in past 24 hours. It seems to be getting more stable.

**Comment by timavo** [comment]
Maybe this can be useful for debugging: I step-by-step build my bot to confirm outstanding trade offers and experienced some weird behaviour regarding this problem. 

In the first step I used the following to get all the trade offers which need to be confirmed:
```
time_conf = Math.floor(Date.now() / 1000);
key_conf = SteamTotp.getConfirmationKey(identity_secret, time_conf, 'conf');

community.getConfirmations(time_conf, key_conf, function (err, confirmations) {
    console.log(err);
    console.log(confirmations);
});
```
All went fine and I got an array of `CConfirmation` objects multiple times (didn't confirm them).

Then I used the following to get the trade offer IDs for each confirmation object:
```
time_conf = Math.floor(Date.now() / 1000);
key_conf = SteamTotp.getConfirmationKey(identity_secret, time_conf, 'conf');

community.getConfirmations(time_conf, key_conf, function (err, confirmations) {
    if (err) { logger.error(err); return; }
    console.log(confirmations);

    time_details = Math.floor(Date.now() / 1000);
    key_details = SteamTotp.getConfirmationKey(identity_secret, time_details, 'details');

    confirmations.forEach(function(confirmation) {
        confirmation.getOfferID(time_details, key_details, function(err, offerID) {
            if (err) { logger.error(err); return; }
            console.log(offerID);
        });
    });
});
```

At first I got the error `[Error: Cannot load confirmation details]` on each `confirmation.getOfferID()` because I used the tag `'conf'` for getting the details. Directly after changing the tag to `'details'` I suddenly got an empty array as response of `community.getConfirmations()`. 

Since then I'm not able to retrieve the information for the 'old' trade offers. After sending two new ones I can get the `offerID` for one of them. The other one returns the error `Error: Cannot load confirmation details`.

**Comment by DoctorMcKay** [comment]
You need to use `conf` for `getConfirmations` and `details` for `getOfferID`. You can't use the same for both.

**Comment by timavo** [comment]
That's what I am doing.

**Comment by scholtzm** [comment]
@DoctorMcKay 1.1% seems to be pretty acceptable, thanks for the stats.

**Comment by infernal079** [comment]
hi i need create new site from iran for send automatic item u can help me ?
